### PR TITLE
destroy kwargs + Before/AfterRun

### PR DESCRIPTION
**Pull request by MatthewCaseres**
This PR makes it explicit that kwargs are banned for `Model`.

Also destroys beforerun and afterrun

### CODE REVIEW

**Comment by MatthewCaseres** [comment]
The cached methods had `sum`, `keys`, and `values` properties. The same reasoning applied in #39 where I try to avoid extra abstractions around the cache leads to me wanting to get rid of these so that people use the Python dictionary API to interact with the cache. Part of work to close out #37 and #40.

I think it is a nice syntax but I feel that the proposed change makes users learn less about this specific system and apply a general understanding of Python to accomplish the same goals.

The reason `.cache` is a property and not attribute is so that cache clearing can be implemented in `Model`. Further refactorings required to implement #5, but these should be non-breaking and additive.

**Comment by lewisfogden** [comment]
For positional, possible quicker to use `/`? At the moment the *arg returns an error anyway if you supply keywords, so probably not worth the run-time hit for the test
https://docs.python.org/3/whatsnew/3.8.html#positional-only-parameters

- Moving signature checks into `Cache.__init__` is much neater!
- Happy to get rid of BeforeRun / AfterRun - given breaking, we need to get semver right?  (or put in a depreciation warning)
- I'd like to keep `.sum()`, `.keys`, `.values` (I use them myself, getting rid of them adds quite a bit of code) - I don't use .keys much.
- I don't think we should encourage too much direct access to the cache, for most uses would encourage people to get the values from the function itself as it is safer (e.g. `sum(proj.num_exits(t) for t in range(12)` to get the total exits for first year).  The dictionary preserves insertion order, which could differ from the user's assumed order.
- Happy to add .cache, however as it is just pointing to the dictionary, perhaps adding a .items() iterator would cut out some of the extra code effort, along the lines of:

```python
def items(self):
    return self._cache.items()
```

**Comment by MatthewCaseres** [comment]
I had no idea about `/` in Python 3.8.

I sort of like the idea of having to explain less things and making the user interact with the library on a more basic level, so my thought was to force them to use the cache. Since that is how my code works currently, getting rid of your features was one path to a unified API.

Given that you enjoy using these features and they will be missed, I will end up shipping them in the LightModel so that the API are uniifed.

Closing this out since none of the changes will ship as is

**Comment by lewisfogden** [comment]
Thanks - appreciate the contribution though :)

**Pull request closed without merging**
